export const GET_ALL_HOME_POST = 'GET_ALL_HOME_POST';
export const GET_ONE_HOME_POST = 'GET_ONE_HOME_POST';
export const SELECT_ONE_HOME_POST = 'SELECT_ONE_HOME_POST';
export const DELETE_HOME_POST = 'DELETE_HOME_POST';
export const CLEAR_HOME_POST = 'CLEAR_HOME_POST';
